org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.249
loader_version_range=[4,)
parchment_mappings_version=2024.11.17
parchment_minecraft_version=1.21.1

mod_id=firstworks
mod_name=Firstworks
mod_license=LGPL-3.0-only
mod_version=0.0.14
mod_group_id=com.nstut.firstworks
