modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="NsTut"
description='''
Gather fibre, bind your first tools, spin rope, tan hides, and process materials in wooden barrels that work directly in the world.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kubejs"
type="optional"
versionRange="[2101.7.2,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jade"
type="optional"
versionRange="[15.10.5,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="jei"
type="optional"
versionRange="[19.43.0,)"
ordering="AFTER"
side="CLIENT"
